import {
  SiX,
  SiInstagram,
  SiYoutube,
  SiTwitch,
  SiGithub,
  SiTiktok,
  SiDiscord,
  SiLinkedin,
  SiSpotify,
  SiPatreon,
  SiKofi,
  SiReddit,
  SiPinterest,
  SiSnapchat,
  SiTelegram,
  SiBluesky,
  SiThreads,
  SiSteam,
  SiSoundcloud,
  SiFacebook,
  SiWhatsapp,
  SiKick,
} from 'react-icons/si'
import {
  UserCircle,
  Link as LinkIcon,
  Link2,
  Gift,
  Shield,
  Crown,
  Settings,
  Lock,
  Globe,
  Key,
  LayoutGrid,
  Plug,
  Image,
  Fingerprint,
} from 'lucide-react'
import type { TabType } from './types'

export const SOCIAL_PLATFORMS = [
  {
    key: 'twitter',
    label: 'X (Twitter)',
    icon: SiX,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#000000',
  },
  {
    key: 'instagram',
    label: 'Instagram',
    icon: SiInstagram,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#E4405F',
  },
  {
    key: 'youtube',
    label: 'YouTube',
    icon: SiYoutube,
    placeholder: '@channel',
    color: '#FFFFFF',
    bgColor: '#FF0000',
  },
  {
    key: 'twitch',
    label: 'Twitch',
    icon: SiTwitch,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#9146FF',
  },
  {
    key: 'tiktok',
    label: 'TikTok',
    icon: SiTiktok,
    placeholder: '@username',
    color: '#FFFFFF',
    bgColor: '#000000',
  },
  {
    key: 'discord',
    label: 'Discord',
    icon: SiDiscord,
    placeholder: 'User ID',
    color: '#FFFFFF',
    bgColor: '#5865F2',
  },
  {
    key: 'github',
    label: 'GitHub',
    icon: SiGithub,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#181717',
  },
] as const

export const ADDITIONAL_PLATFORMS = [
  {
    key: 'bluesky',
    label: 'Bluesky',
    icon: SiBluesky,
    placeholder: 'handle.bsky.social',
    color: '#FFFFFF',
    bgColor: '#0085FF',
  },
  {
    key: 'threads',
    label: 'Threads',
    icon: SiThreads,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#000000',
  },
  {
    key: 'kick',
    label: 'Kick',
    icon: SiKick,
    placeholder: 'username',
    color: '#53FC18',
    bgColor: '#0D0E0F',
  },
  {
    key: 'linkedin',
    label: 'LinkedIn',
    icon: SiLinkedin,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#0A66C2',
  },
  {
    key: 'facebook',
    label: 'Facebook',
    icon: SiFacebook,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#1877F2',
  },
  {
    key: 'reddit',
    label: 'Reddit',
    icon: SiReddit,
    placeholder: 'u/username',
    color: '#FFFFFF',
    bgColor: '#FF4500',
  },
  {
    key: 'pinterest',
    label: 'Pinterest',
    icon: SiPinterest,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#BD081C',
  },
  {
    key: 'snapchat',
    label: 'Snapchat',
    icon: SiSnapchat,
    placeholder: 'username',
    color: '#000000',
    bgColor: '#FFFC00',
  },
  {
    key: 'telegram',
    label: 'Telegram',
    icon: SiTelegram,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#26A5E4',
  },
  {
    key: 'whatsapp',
    label: 'WhatsApp',
    icon: SiWhatsapp,
    placeholder: 'phone number',
    color: '#FFFFFF',
    bgColor: '#25D366',
  },
  {
    key: 'spotify',
    label: 'Spotify',
    icon: SiSpotify,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#1DB954',
  },
  {
    key: 'soundcloud',
    label: 'SoundCloud',
    icon: SiSoundcloud,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#FF5500',
  },
  {
    key: 'steam',
    label: 'Steam',
    icon: SiSteam,
    placeholder: 'profile ID',
    color: '#FFFFFF',
    bgColor: '#171A21',
  },
  {
    key: 'patreon',
    label: 'Patreon',
    icon: SiPatreon,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#FF424D',
  },
  {
    key: 'kofi',
    label: 'Ko-fi',
    icon: SiKofi,
    placeholder: 'username',
    color: '#FFFFFF',
    bgColor: '#FF5E5B',
  },
] as const

export const ALL_SOCIAL_PLATFORMS = [
  ...SOCIAL_PLATFORMS,
  ...ADDITIONAL_PLATFORMS,
] as const

export function getPlatformByKey(key: string) {
  return (
    ALL_SOCIAL_PLATFORMS.find((p) => p.key === key) || {
      key,
      label: key,
      icon: Globe,
      placeholder: 'username',
      color: '#6366f1',
      bgColor: '#6366f1',
    }
  )
}

export const CREATOR_TYPES = [
  { value: '', label: 'Select type...' },
  { value: 'vtuber', label: 'VTuber' },
  { value: 'screentuber', label: 'ScreenTuber' },
  { value: 'streamer', label: 'Streamer' },
  { value: 'artist', label: 'Artist' },
  { value: 'musician', label: 'Musician' },
  { value: 'developer', label: 'Developer' },
  { value: 'content_creator', label: 'Content Creator' },
  { value: 'gamer', label: 'Gamer' },
  { value: 'other', label: 'Other' },
] as const

export const PRONOUNS_OPTIONS = [
  { value: 'none', label: 'Select...' },
  { value: 'he/him', label: 'He/Him' },
  { value: 'she/her', label: 'She/Her' },
  { value: 'they/them', label: 'They/Them' },
  { value: 'any', label: 'Any' },
  { value: 'custom', label: 'Custom' },
] as const

export const DASHBOARD_TABS: Array<{
  id: TabType
  labelKey: string
  descKey: string
  icon: typeof UserCircle
  category: 'main' | 'premium' | 'account'
}> = [
  {
    id: 'profile',
    labelKey: 'dashboard.tabs.profile',
    descKey: 'dashboard.tabs.profileDesc',
    icon: UserCircle,
    category: 'main',
  },
  {
    id: 'links',
    labelKey: 'dashboard.tabs.links',
    descKey: 'dashboard.tabs.linksDesc',
    icon: LinkIcon,
    category: 'main',
  },
  {
    id: 'shortener',
    labelKey: 'dashboard.tabs.shortener',
    descKey: 'dashboard.tabs.shortenerDesc',
    icon: Link2,
    category: 'main',
  },
  {
    id: 'widgets',
    labelKey: 'dashboard.tabs.widgets',
    descKey: 'dashboard.tabs.widgetsDesc',
    icon: LayoutGrid,
    category: 'main',
  },
  {
    id: 'integrations',
    labelKey: 'dashboard.tabs.integrations',
    descKey: 'dashboard.tabs.integrationsDesc',
    icon: Plug,
    category: 'main',
  },
  {
    id: 'media',
    labelKey: 'dashboard.tabs.media',
    descKey: 'dashboard.tabs.mediaDesc',
    icon: Image,
    category: 'main',
  },
  {
    id: 'referrals',
    labelKey: 'dashboard.tabs.referrals',
    descKey: 'dashboard.tabs.referralsDesc',
    icon: Gift,
    category: 'main',
  },
  {
    id: 'badges',
    labelKey: 'dashboard.tabs.badges',
    descKey: 'dashboard.tabs.badgesDesc',
    icon: Shield,
    category: 'main',
  },
  {
    id: 'subscription',
    labelKey: 'dashboard.tabs.subscription',
    descKey: 'dashboard.tabs.subscriptionDesc',
    icon: Crown,
    category: 'premium',
  },
  {
    id: 'api',
    labelKey: 'dashboard.tabs.api',
    descKey: 'dashboard.tabs.apiDesc',
    icon: Key,
    category: 'premium',
  },
  {
    id: 'settings',
    labelKey: 'dashboard.tabs.settings',
    descKey: 'dashboard.tabs.settingsDesc',
    icon: Settings,
    category: 'account',
  },
  {
    id: 'privacy',
    labelKey: 'dashboard.tabs.privacy',
    descKey: 'dashboard.tabs.privacyDesc',
    icon: Lock,
    category: 'account',
  },
  {
    id: 'security',
    labelKey: 'dashboard.tabs.security',
    descKey: 'dashboard.tabs.securityDesc',
    icon: Fingerprint,
    category: 'account',
  },
]
