/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as BioRouteImport } from './routes/_bio'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api/spotify-callback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicTemplatesRouteImport } from './routes/_public/templates'
import { Route as PublicStatusRouteImport } from './routes/_public/status'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicPartnersRouteImport } from './routes/_public/partners'
import { Route as PublicLeaderboardRouteImport } from './routes/_public/leaderboard'
import { Route as PublicCreatorsRouteImport } from './routes/_public/creators'
import { Route as PublicCookiesRouteImport } from './routes/_public/cookies'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedThemeBuilderRouteImport } from './routes/_protected/theme-builder'
import { Route as ProtectedReferralsRouteImport } from './routes/_protected/referrals'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPlaygroundRouteImport } from './routes/_protected/playground'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as BioUsernameRouteImport } from './routes/_bio/$username'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ApiSitemapRouteImport } from './routes/_api/sitemap'
import { Route as ApiRssRouteImport } from './routes/_api/rss'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as PublicSCodeRouteImport } from './routes/_public/s.$code'
import { Route as PublicJoinCodeRouteImport } from './routes/_public/join.$code'
import { Route as ProtectedAdminPartnerApplicationsRouteImport } from './routes/_protected/admin/partner-applications'
import { Route as ApiWebhooksStripeRouteImport } from './routes/_api/webhooks/stripe'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/_bio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify-callback',
  path: '/api/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTemplatesRoute = PublicTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartnersRoute = PublicPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeaderboardRoute = PublicLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCreatorsRoute = PublicCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedThemeBuilderRoute = ProtectedThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReferralsRoute = ProtectedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlaygroundRoute = ProtectedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const BioUsernameRoute = BioUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => BioRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/_api/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssRoute = ApiRssRouteImport.update({
  id: '/_api/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicSCodeRoute = PublicSCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => PublicRoute,
} as any)
const PublicJoinCodeRoute = PublicJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedAdminPartnerApplicationsRoute =
  ProtectedAdminPartnerApplicationsRouteImport.update({
    id: '/admin/partner-applications',
    path: '/admin/partner-applications',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/_api/webhooks/stripe',
  path: '/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/hello': typeof ApiHelloRoute
  '/rss': typeof ApiRssRoute
  '/sitemap': typeof ApiSitemapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof BioUsernameRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/playground': typeof ProtectedPlaygroundRoute
  '/profile': typeof ProtectedProfileRoute
  '/referrals': typeof ProtectedReferralsRoute
  '/theme-builder': typeof ProtectedThemeBuilderRoute
  '/about': typeof PublicAboutRoute
  '/changelog': typeof PublicChangelogRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/creators': typeof PublicCreatorsRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/partners': typeof PublicPartnersRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/status': typeof PublicStatusRoute
  '/templates': typeof PublicTemplatesRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/': typeof PublicIndexRoute
  '/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/partner-applications': typeof ProtectedAdminPartnerApplicationsRoute
  '/join/$code': typeof PublicJoinCodeRoute
  '/s/$code': typeof PublicSCodeRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/hello': typeof ApiHelloRoute
  '/rss': typeof ApiRssRoute
  '/sitemap': typeof ApiSitemapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof BioUsernameRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/playground': typeof ProtectedPlaygroundRoute
  '/profile': typeof ProtectedProfileRoute
  '/referrals': typeof ProtectedReferralsRoute
  '/theme-builder': typeof ProtectedThemeBuilderRoute
  '/about': typeof PublicAboutRoute
  '/changelog': typeof PublicChangelogRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/creators': typeof PublicCreatorsRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/partners': typeof PublicPartnersRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/status': typeof PublicStatusRoute
  '/templates': typeof PublicTemplatesRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/': typeof PublicIndexRoute
  '/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/partner-applications': typeof ProtectedAdminPartnerApplicationsRoute
  '/join/$code': typeof PublicJoinCodeRoute
  '/s/$code': typeof PublicSCodeRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_bio': typeof BioRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_api/rss': typeof ApiRssRoute
  '/_api/sitemap': typeof ApiSitemapRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_bio/$username': typeof BioUsernameRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/playground': typeof ProtectedPlaygroundRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/referrals': typeof ProtectedReferralsRoute
  '/_protected/theme-builder': typeof ProtectedThemeBuilderRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/creators': typeof PublicCreatorsRoute
  '/_public/leaderboard': typeof PublicLeaderboardRoute
  '/_public/partners': typeof PublicPartnersRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/templates': typeof PublicTemplatesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/spotify-callback': typeof ApiSpotifyCallbackRoute
  '/_public/': typeof PublicIndexRoute
  '/_api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_protected/admin/partner-applications': typeof ProtectedAdminPartnerApplicationsRoute
  '/_public/join/$code': typeof PublicJoinCodeRoute
  '/_public/s/$code': typeof PublicSCodeRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hello'
    | '/rss'
    | '/sitemap'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/$username'
    | '/analytics'
    | '/playground'
    | '/profile'
    | '/referrals'
    | '/theme-builder'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/creators'
    | '/leaderboard'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/templates'
    | '/terms'
    | '/verify-email'
    | '/api/health'
    | '/api/spotify-callback'
    | '/'
    | '/webhooks/stripe'
    | '/admin/partner-applications'
    | '/join/$code'
    | '/s/$code'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/rss'
    | '/sitemap'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/$username'
    | '/analytics'
    | '/playground'
    | '/profile'
    | '/referrals'
    | '/theme-builder'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/creators'
    | '/leaderboard'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/templates'
    | '/terms'
    | '/verify-email'
    | '/api/health'
    | '/api/spotify-callback'
    | '/'
    | '/webhooks/stripe'
    | '/admin/partner-applications'
    | '/join/$code'
    | '/s/$code'
    | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/_bio'
    | '/_protected'
    | '/_public'
    | '/_api/hello'
    | '/_api/rss'
    | '/_api/sitemap'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_bio/$username'
    | '/_protected/analytics'
    | '/_protected/playground'
    | '/_protected/profile'
    | '/_protected/referrals'
    | '/_protected/theme-builder'
    | '/_public/about'
    | '/_public/changelog'
    | '/_public/contact'
    | '/_public/cookies'
    | '/_public/creators'
    | '/_public/leaderboard'
    | '/_public/partners'
    | '/_public/pricing'
    | '/_public/privacy'
    | '/_public/status'
    | '/_public/templates'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/api/health'
    | '/api/spotify-callback'
    | '/_public/'
    | '/_api/webhooks/stripe'
    | '/_protected/admin/partner-applications'
    | '/_public/join/$code'
    | '/_public/s/$code'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  BioRoute: typeof BioRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
  ApiRssRoute: typeof ApiRssRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bio': {
      id: '/_bio'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/spotify-callback': {
      id: '/api/spotify-callback'
      path: '/api/spotify-callback'
      fullPath: '/api/spotify-callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/templates': {
      id: '/_public/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof PublicTemplatesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/partners': {
      id: '/_public/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PublicPartnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/leaderboard': {
      id: '/_public/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PublicLeaderboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/creators': {
      id: '/_public/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof PublicCreatorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/theme-builder': {
      id: '/_protected/theme-builder'
      path: '/theme-builder'
      fullPath: '/theme-builder'
      preLoaderRoute: typeof ProtectedThemeBuilderRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/referrals': {
      id: '/_protected/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ProtectedReferralsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/playground': {
      id: '/_protected/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof ProtectedPlaygroundRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_bio/$username': {
      id: '/_bio/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof BioUsernameRouteImport
      parentRoute: typeof BioRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/sitemap': {
      id: '/_api/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/rss': {
      id: '/_api/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof ApiRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/s/$code': {
      id: '/_public/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof PublicSCodeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/join/$code': {
      id: '/_public/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof PublicJoinCodeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/admin/partner-applications': {
      id: '/_protected/admin/partner-applications'
      path: '/admin/partner-applications'
      fullPath: '/admin/partner-applications'
      preLoaderRoute: typeof ProtectedAdminPartnerApplicationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_api/webhooks/stripe': {
      id: '/_api/webhooks/stripe'
      path: '/webhooks/stripe'
      fullPath: '/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BioRouteChildren {
  BioUsernameRoute: typeof BioUsernameRoute
}

const BioRouteChildren: BioRouteChildren = {
  BioUsernameRoute: BioUsernameRoute,
}

const BioRouteWithChildren = BioRoute._addFileChildren(BioRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedPlaygroundRoute: typeof ProtectedPlaygroundRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedReferralsRoute: typeof ProtectedReferralsRoute
  ProtectedThemeBuilderRoute: typeof ProtectedThemeBuilderRoute
  ProtectedAdminPartnerApplicationsRoute: typeof ProtectedAdminPartnerApplicationsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedPlaygroundRoute: ProtectedPlaygroundRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedReferralsRoute: ProtectedReferralsRoute,
  ProtectedThemeBuilderRoute: ProtectedThemeBuilderRoute,
  ProtectedAdminPartnerApplicationsRoute:
    ProtectedAdminPartnerApplicationsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicCreatorsRoute: typeof PublicCreatorsRoute
  PublicLeaderboardRoute: typeof PublicLeaderboardRoute
  PublicPartnersRoute: typeof PublicPartnersRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicTemplatesRoute: typeof PublicTemplatesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicJoinCodeRoute: typeof PublicJoinCodeRoute
  PublicSCodeRoute: typeof PublicSCodeRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicChangelogRoute: PublicChangelogRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicCreatorsRoute: PublicCreatorsRoute,
  PublicLeaderboardRoute: PublicLeaderboardRoute,
  PublicPartnersRoute: PublicPartnersRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicTemplatesRoute: PublicTemplatesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicJoinCodeRoute: PublicJoinCodeRoute,
  PublicSCodeRoute: PublicSCodeRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  BioRoute: BioRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
  ApiRssRoute: ApiRssRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
